service: appointment-scheduler

#frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: dev
  environment:
    DYNAMODB_ENDPOINT: http://localhost:4200 
    DYNAMODB_PATIENTS_TABLE: ${self:service}-${self:provider.stage}-patients
    DYNAMODB_DOCTORS_TABLE: ${self:service}-${self:provider.stage}-doctors
    DYNAMODB_APPOINTMENTS_TABLE: ${self:service}-${self:provider.stage}-appointments
    DYNAMODB_USERS_TABLE: ${self:service}-${self:provider.stage}-users
    DYNAMODB_COUNTRIES_TABLE: ${self:service}-${self:provider.stage}-countries

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PATIENTS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_DOCTORS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_APPOINTMENTS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_USERS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_COUNTRIES_TABLE}"

functions:
  createPatient:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: patients
          method: post
          cors: true
  getAllPatient:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: patients
          method: get
          cors: true
  createCountry:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: countries
          method: post
          cors: true

  createDoctor:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: doctors
          method: post
          cors: true
  getAllDoctor:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: doctors
          method: get
          cors: true
  createAppointment:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: appointments
          method: post
          cors: true
  getAllAppointment:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: appointments
          method: get
          cors: true
  getAppointmentsByCountryId:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: appointments/country/{countryId}
          method: get
          cors: true
  getAppointmentsByDoctorId:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: appointments/doctor/{doctorId}
          method: get
          cors: true
  getAppointmentsByCountryAndDoctor:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: appointments/country/{countryId}/doctor/{doctorId}
          method: get
          cors: true
resources:
  Resources:
    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_PATIENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: patientId
            AttributeType: S
        KeySchema:
          - AttributeName: patientId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DoctorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_DOCTORS_TABLE}
        AttributeDefinitions:
          - AttributeName: doctorId
            AttributeType: S
        KeySchema:
          - AttributeName: doctorId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_APPOINTMENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: countryId
            AttributeType: S
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: countryId
            KeyType: HASH
          - AttributeName: appointmentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CountriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_COUNTRIES_TABLE}
        AttributeDefinitions:
          - AttributeName: countryId
            AttributeType: S
        KeySchema:
          - AttributeName: countryId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  #- serverless-dynamodb-local

# custom:
#   dynamodb:
#     start:
#       port: 8000
#       inMemory: true
#       heapInitial: 200m
#       heapMax: 1g
#       migrate: true
#     stages:
#       - dev
